version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./movie-tycoon
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
    volumes:
      - ./movie-tycoon:/app
    depends_on:
      - backend
    restart: unless-stopped 